### PR TITLE
Defensive coding in atom link

### PR DESCRIPTION
**Pull request by ploeh**
The purpose of this PR is mainly to be able to better to troubleshoot #69 by adding some more explicit exception messages.

### CODE REVIEW

**Comment by sgryt** [comment]
Maybe include the value of the `href` attribute in the exception message when the `rel` attribute is missing, to further aid the diagnostics?
And perhaps include the `rel` value (if present) in the exception message, when the `href` is missing?

**Comment by ploeh** [comment]
That may be an idea, but on the other hand, that might introduce additional complexity, because that would mean that the code would also have to check for null for the other value...

Let's see if this is enough to troubleshoot, of if more diagnostics are required...

**Comment by sgryt** [comment]
I know, but IME, you never can get too much information when troubleshooting that kind of failure :)

**Comment by ploeh** [comment]
I hear you :)

**Pull request merged**
