### PR TITLE
Silently fail update of last link

### PR DESCRIPTION
**Pull request by ploeh**

### CODE REVIEW

**Comment by ploeh** [comment]
The purpose of this pull request is to address #96.

**Comment by sgryt** [comment]
It _looks_ correct. Two things spring to mind, though (now that we are not in happy-path testing territory). 
- What happens if the index write repeatedly fails after crossing a page size boundary? From reading the code and added tests, it appears to be handled well enough by the fact that ReadLastPage always reads all the way to the end of pages, but the implementation is a little bit too complicated for me to be entirely sure. 
-  (a variation of the case above): What happens if the index write repeatedly fails across several page size boundaries (same consideration as above apply)?

I'm not entirely sure how one would go about adding tests for these cases, as, if the implementation is indeed correct, such tests would not fail, but maybe a few, well-chosen temporary implementation 'disablings', could do the trick.

**Comment by ploeh** [comment]
PR updated with more test cases.

In summary, upon repeated failure of update of the index document, the events are still written, but the access time becomes more and more inefficient.

Agreed that the implementation code is a mess, but I didn't want to refactor it before I knew that it had the correct behaviour.

**Comment by sgryt** [comment]
No further comments - I believe it works as intended now. At least, I have failed to detect any logical flaws or implementation problems.

**Comment by ploeh** [comment]
OK, will you pull, then?

**Comment by sgryt** [comment]
Certainly - done now.

**Comment by ploeh** [comment]
Thank you :+1:

**Pull request merged**
