### PR TITLE
Fixed a bug with sealed event classes.

### PR DESCRIPTION
**Pull request by ploeh**

### CODE REVIEW

**Comment by sgryt** [comment]
Oh, nice trick! I did not know that..

I have no other comments, so if you need this really bad, feel free to rebase master.

**Comment by ploeh** [comment]
Nah, it's not 'nice' by any definition of the word, but unfortunately necessary.

I'll rebase this when I need it - which I suspect will be before Thursday...

**Comment by sgryt** [comment]
Just for reference, I got this test error after rebasing master on this PR:

```
Test 'Grean.AtomEventStore.UnitTests.XmlAtomContentTests.SutCanSerializeEventWithDateTimeOffset(seed: Grean.AtomEventStore.XmlAtomContent, ted: Grean.AtomEventStore.UnitTests.TestEventD)' failed:
    Assert.Equal() Failure
Expected: <content type="application/xml" xmlns="http://www.w3.org/2005/Atom">
            <test-event-d xmlns="urn:grean:atom-event-store:unit-tests">
              <number>102</number>
              <date-time>2012-07-10T14:50:04.3880280+02:00</date-time>
            </test-event-d>
          </content>
Actual:   <content type="application/xml" xmlns="http://www.w3.org/2005/Atom">
            <test-event-d xmlns="urn:grean:atom-event-store:unit-tests">
              <number>102</number>
              <date-time>2012-07-10T14:50:04.388028+02:00</date-time>
            </test-event-d>
          </content>
    XmlAtomContentTests.cs(422,0): at Grean.AtomEventStore.UnitTests.XmlAtomContentTests.SutCanSerializeEventWithDateTimeOffset(XmlAtomContent seed, TestEventD ted)

143 passed, 1 failed, 0 skipped, took 1.93 seconds (xUnit.net 1.9.1 build 1600).
```

It did not fail when running the test suite on the branch itself, and I haven't been able to reproduce the failure.
But it seems we have a case of datetime-offset edge case - I can't say why the extra '0' in the date-time field of the Expected xml string appears.

**Comment by ploeh** [comment]
It's a known, intermittent test failure, and as such a pain in the ass... It seems to be caused by lack of serialization/deserialization precision of `DateTimeOffset` instances. If you look closely, you'll notice that the expected and actual `date-time` values are unequal:

> 2012-07-10T14:50:04.3880280+02:00
> 2012-07-10T14:50:04.388028+02:00

Suggestions for a fix are velcome.

**Comment by sgryt** [comment]
I would say that a trailing zero in the fractional seconds part does not make the `DateTimeOffset` instances different, and it kind of boggles the mind as to why the traililng zero is there in the first place.

But anyway, an intermittent failure it probably is - and live with it we must, suppose I.

**Pull request merged**
