### PR TITLE
No read forward before first element

### PR DESCRIPTION
**Pull request by ploeh**

### CODE REVIEW

**Comment by sgryt** [comment]
Gr8, will run a measurement on this asap. 

We have a task on updating the NuGet packages in the standalone CatalogSvc, do you have time for that? Otherwise, could you point me to the PR(s) where you did the same for the frontend-hosted version?

**Comment by sgryt** [comment]
IIRC, there was something about needing to update the blob data?

**Comment by ploeh** [comment]
Version 0.9.2 is now published to MyGet.

Indeed, compared to the version currently in use, there's a breaking change, because all BLOBs should be renamed to have the .xml extension: https://github.com/GreanTech/AtomEventStore/releases/tag/v0.6.0

**Comment by sgryt** [comment]
Is it possible to have the two data file names co-exist in the blob container?

**Comment by sgryt** [comment]
Follow-up: Possible as in 'not breaking the code'?

**Comment by ploeh** [comment]
Yes, but we just need to ensure that no writes happen while duplicates exist, because otherwise we may lose an update.

**Pull request merged**
