### PR TITLE
Update AtomAuthor.cs

### PR DESCRIPTION
**Pull request by Jaxwood**
Fixed spelling error

### CODE REVIEW

**Comment by ploeh** [comment]
Thank you for your contribution! It's now live as [AtomEventStore 1.7.1](https://www.nuget.org/packages/AtomEventStore/1.7.1).

**Comment by ploeh** [comment]
@Jaxwood I just noticed that you haven't signed the CLA, so I shouldn't have pulled your contribution just yet. That's my fault.

If you will [sign the CLA](https://www.clahub.com/agreements/GreanTech/AtomEventStore), we'd much appreciate it. Otherwise, for legal reasons, I'll have to revert the changes.

Sorry about the inconvenience.

**Comment by Jaxwood** [comment]
I've signed it :+1: no problem.

**Comment by ploeh** [comment]
Great! Thank you, and sorry about the inconvenience. It looks like perhaps GitHub reports the status incorrectly, but I see your signature on CLAHub, and that's what counts :)

**Comment by samprogram** [comment]
Yeah, because you would otherwise _totally_ have gotten sued over changing `saingle` to `single` in a code comment. What the f_cking f_ck???!

**Pull request merged**
