### PR TITLE
Enabled building from cmd line when only VS2013 is

### PR DESCRIPTION
**Pull request by ploeh**
installed on a system.

### CODE REVIEW

**Comment by ploeh** [comment]
I've tested this on my other machine, running Windows 7 and Visual Studio 2012, and it works well there too.

**Comment by sgryt** [comment]
I've got some mixed results on this one. Works fine on my VS2012 box, but the first run of `build-release.sh` failed on my 2013 box with:

c:\Users\Mikkel\Documents\Source\Repos\AtomEventStore\BuildRelease.msbuild(29,5
): error : The xunit task requires either Assembly or Assemblies, but not both.
Done Building Project "c:\Users\Mikkel\Documents\Source\Repos\AtomEventStore\Bu
ildRelease.msbuild" (default targets) -- FAILED.

I then opened the solution in VS2013, and started a build - which triggered a NuGet Package Restore. Solution compiled fine after that. I ran the test (rather, nCrunch did) and they passed. Going back to the Git Bash prompt, the previous error was no longer reproducible. 

I will pull the PR as I cannot repro the problem, would just like to leave a note here, in case we see the problem again on a clean VS 2013 box.

**Comment by ploeh** [comment]
I've seen this behaviour as well, and I think it's an issue with the xUnit.net MSBuild task.

If you attempt to build a completely blank project/solution, somehow, the xUnit.net MSBuild task doesn't pick up the compiled test binaries.

If you attempt to repeat the build, IME it always succeeds.

BTW, you really should [disable NuGet Package Restore](http://blog.ploeh.dk/2014/01/29/nuget-package-restore-considered-harmful) :)

**Comment by sgryt** [comment]
Erh, I did not realize that I had enabled that...but I can see why that is, from your link to the NuGet v2.7 release notes. Yikes...

**Pull request merged**
