### PR TITLE
Prepending writer

### PR DESCRIPTION
**Pull request by ploeh**
Still a Work in Progress...

### CODE REVIEW

**Comment by sgryt** [comment]
How come there is still a need to `Reverse()` the events on a page?

**Comment by sgryt** [comment]
- just seems a bit counterintuitive, now that we are starting from a pointer to the beginning of time :)

**Comment by ploeh** [comment]
I'm just going with Atom, where the convention is that the most recent entries appear on top of a page.

(It may actually be more than a convention... It may actually be in the Atom specification, but I haven't looked it up, so I'm just calling it a _convention_ here...)

**Comment by sgryt** [comment]
I see. In the degenerate case of infinite page size (ok, not infinite, but int.MaxSize, or just a very large page size) that convention will bite clients the same way that the current implementation does. Can we allow ourselves to stray from that convention ?

**Comment by ploeh** [comment]
In reality, that's not going to be a problem, because if a client sets the page size that high, the overall system will have other problems. Assume that the page size is _l_, where _l_ is a very large number (perhaps `Int32.MaxValue`).
- The size of an almost full page will be _l_ \* the average size of of a serialized event. That size is likely to surpass the amount of RAM in the system, because an XML-serialized event can easily be 1 kB. We're talking about single files in the TB range, here.
- Writing a new entry to an almost full page will be slow, because first the client will need to read the file, and then write the updated file back to storage. If this happens over a network, it's going to take some time. Even with a Gigabit network, we're talking several seconds, or even minutes.

The reason we've made page size configurable is because the best page size is a balance between optimizing for writing and optimizing for reading. [We've seen this before: as the page size goes up, read speed increases, but write speed decreases](https://github.com/GreanTech/AtomEventStore/pull/30)

We could consider changing the `pageSize` argument to an `Int16` or even a `Byte`, but I don't think it's necessary, since I doubt that this is going to be a real problem.

**Comment by sgryt** [comment]
Makes sense, let's leave it at that. I guess this is the limit where we stop securing people from shooting themselves in the foot :)

**Pull request merged**
