### PR TITLE
Xml content serializer

### PR DESCRIPTION
**Pull request by ploeh**
This feature may not be done, but I think it's heading in the right direction. However, feedback is appreciated.

### CODE REVIEW

**Comment by sgryt** [comment]
It looks like a useful feature, but I'm not entirely sure why we need it ?

**Comment by ploeh** [comment]
Oh, we need it because the current `ConventionBasedSerializerOfComplexImmutableClasses` Strategy isn't going to work with F# (or, not very well, at least).

In F#, it would be much better to model events as record types. If we adorn them with various attributes, we'll [be able to serialize them, but from the F# code's perspective, they _still look like immutable record types_](http://blog.ploeh.dk/2013/10/15/easy-aspnet-web-api-dtos-with-f-climutable-records).

I have to admit that I've yet to make a complete [Facade Test](http://blog.ploeh.dk/2012/06/27/FacadeTest) of that entire feature, but if I'm not much mistaken, we should be able to define an event like this, and it would just work:

``` F#
[<CLIMutable>]
[<XmlRoot("my-event", Namespace = "http://grean.is.great")>]
type MyEvent = {
    Text : string
    Number : int }
```

Apart from the F# support, I'm thinking that we should consider retiring the `ConventionBasedSerializerOfComplexImmutableClasses` class. On some levels, it's pretty cool, but it's also a bit shaky. At least, if we're going to open source AtomEventStore (which I'd really like to do), I think we need to supply some alternatives. At least a serializer based on `XmlSerializer`, and another based on `DataContractSerializer`. Some people might even want a JSON serializer, although personally, I think it's a bit perverse to put JSON inside XML.

However, if you'd prefer me to add a Facade Test to this PR before you will consider accepting it, I'm OK with that. I just issued the PR in order to get some early feedback.

**Comment by sgryt** [comment]
Ah, I see. Interesting, to have you as a proponent for using custom attributes :) Not entirely unexpected, given the frequent use of such ones in AutoFixture, but IIRC, you raged a bit against them a while back ?

Especially the CLIMutable one seems like a very pragmatic approach to gaming the system (mutable, yet immutable, F# record types). Maybe we should name them 'Schrödinger Records'. Reminds me of my old habit of using `System.Runtime.Serialization.FormatterServices.GetUninitializedObject(Type type)` in unit test suites...

Anyway, I just wanted a clue as of to where this was heading, and now that I have it, I'll accept the PR.

**Comment by ploeh** [comment]
It's not that I've suddenly embraced attributes again, but at a pragmatic level, this may be a better approach at the moment...

**Pull request merged**
